### ISSUE TITLE
lvm_volume_group hangs forever reading [y/n] if signature detected on disk

### ISSUE THREAD

**Issue by irvingpop** [chef-cookbooks/lvm#45]
Testing lvm on RHEL7, it has become pickier:

```
[root@ip-rh-backend1 ~]# vgcreate opscode  /dev/xvdb
WARNING: ext3 signature detected on /dev/xvdb at offset 1080. Wipe it? [y/n]
```

Unfortunately in chef-client runs this seems to just hang indefinitely waiting on the input.   I hadn't experienced this previously in RHEL5 or 6, nor Ubuntu 12.04 or 14.04. 

Some possible solutions:
1.  Add a "force" method which appends -y to vgcreate
2. Attempt to detect a signature the same way lvm does, and bomb proactively
3. the di-ruby-lvm gem uses passes `raw` along to Open4 without a timeout.   Maybe use shell_out directly instead of lvm.raw?

**Comment by juliandunn** [comment]
"force" seems like a bad thing to pass to `vgcreate`. I like option 2.

I've had similar problems with interactive output causing Chef to consume all memory and hang forever: https://tickets.opscode.com/browse/CHEF-4794 (not sure if you ended up having memory exhaustion or not)

**Comment by lopaka** [comment]
We just ran into this issue with CentOS 7 and RHEL 7.  I was surprised that there was no attribute to pass in common command line options.  Perhaps an 'options' attribute or an attribute specific to ignore warnings, or answer yes to questions.  Having to run `wipefs` before hand looks to be our method for now.

**Comment by jplinux** [comment]
Same matter with lvcreate. Solved by adding these options '-y -Wy -Zy' to lvcreate instruction within cookbooks/lvm/libraries/provider_lvm_logical_volume.rb

**Comment by max-lobur** [comment]
@jplinux having same problem on CentOS 7. " -y -Wy -Zy" works for me.
I do find -Wy and -Zy meaning, but what is -y? Appreciate the feedback

**Comment by irvingpop** [comment]
I got frustrated with RHEL7's lvm and made this PR:  https://github.com/chef-cookbooks/lvm/pull/74

**Comment by tas50** [comment]
This is fixed in the latest release thanks to @irvingpop

**Comment by davecozz** [comment]
I'm still running into this issue with lvcreate on RHEL7 with the latest version (1.6.1).  


 `  * lvm_logical_volume[my_vol] action create[2016-03-29T19:59:48+00:00] INFO: Processing lvm_logical_volume[my_vol] action create (my-cookbook::my-recipe line 58)
 [2016-03-29T19:59:48+00:00] DEBUG: Executing lvm command: 'lvcreate --size 5G       --name my_vol myvg '`

This is what it's getting caught up on: 

`  WARNING: ext4 signature detected on /dev/myvg/my_vol at offset 1080. Wipe it? [y/n]:  `

**Comment by irvingpop** [comment]
hey @davecozz the option I added was at the VG level (seemed more productive there) - are you saying that in your setup, `lvm` is allowing you to create the VG over preexisting data, but then barfs when creating the LV?

**Comment by irvingpop** [comment]
@davecozz what happens if you wrap the `lvm_logical_volume` inside of the `lvm_volume_group` like so:

```ruby
lvm_volume_group 'myvg' do
  physical_volumes ['/dev/vdb']
  wipe_signatures true

  logical_volume 'my_vol' do
    size '5G'
    filesystem 'ext4'
    mount_point '/some/dir'
  end
end
```

also, is the behavior different on an existing machine that already has VG `myvg` in place, vs a new machine that doesn't?

**Comment by davecozz** [comment]
@irvingpop OK, I wrapped all of the `logical_volume` resources (about 2-5 per recipe) inside of a `lvm_volume_group` but I still get the same issue. 

However, previously it was inconsistently hanging but now it seems to get stuck in the same spot regularly. There's a temporary lv that gets created, deleted, and then if it tries to get created again it gets stuck on that lvcreate: 

`WARNING: ext4 signature detected on /dev/myvg/vol_tempfs at offset 1080. Wipe it? [y/n]: `

**Comment by irvingpop** [comment]
@davecozz I'm thinking that `logical_volume` will need an equivalent argument in order to meet your use case then.

**Comment by alexs77** [comment]
I cloned the source on 2016-08-16 and have the same issue on a Ubuntu 16.04 system. I'm having "plain" `lvm_logical_volume` directly in my recipe; ie. *not* wrapped in a `lvm_volume_group` block: Doing that, because I don't want the cookbook to create a volume group, but just some logical volumes.

There ought to be a `wipe_signatures true` for the `lvm_logical_volume` as well.

**Comment by alexs77** [comment]
**Update with workaround:**

Thanks to the [comment](https://github.com/chef-cookbooks/lvm/issues/45#issuecomment-112032126) from @jplinux on [15 Jun 2015](https://github.com/chef-cookbooks/lvm/issues/45#issuecomment-112032126), I had a look at **[lvm/libraries/provider_lvm_logical_volume.rb line 238](https://github.com/chef-cookbooks/lvm/blob/master/libraries/provider_lvm_logical_volume.rb#L238)** and found **`lv_params = new_resource.lv_params`** there. I now have this in my recipe:

```ruby
            lvm_logical_volume "test5" do
                group 'system'
                size '500m'
                filesystem 'ext4'
                mount_point location: '/test5', options: 'noatime,nodiratime', dump: 0, pass: 2
                # https://github.com/chef-cookbooks/lvm/issues/45#issuecomment-112032126
                # lvcreate mit '-y -Wy -Zy' aufrufen
                lv_params '-y -Wy -Zy'
            end # of lvm_logical_volume "Erstelle LV #{vgname}/#{lvname}" do
```

*Works for me* :laughing:
